# Dockerfile to build CorsixTH
FROM ubuntu:latest

WORKDIR /sourcecode

RUN apt-get update && apt-get install -y build-essential cmake git liblua5.2-0 liblua5.2-dev libsdl2-dev libsdl2-mixer-dev timidity libfreetype6-dev lua-filesystem lua-lpeg doxygen liblua5.3-0 liblua5.3-0-dbg liblua5.3-dev ffmpeg libavcodec-dev libavformat-dev libavresample-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libpostproc-dev libswresample-dev

CMD mkdir build && cd build && cmake -DUSE_SOURCE_DATADIRS=ON .. && make
