### CorsixTH Enhancement Template ###
### Headers
name: Feature request
description: Suggest an idea for this project
title: "Give a feature/enhancement summary"
labels: ["enhancement"]
### Questions
# What is wanted?
body:
  - type: textarea
    id: subjectof
    attributes:
      label: What feature or enhancement would you like to add?
      description: Include a description of what feature/enahcement you would like to see in CorsixTH
    validations:
      required: true
# The benefits
  - type: textarea
    id: benefits
    attributes:
      label: How would this feature benefit the gameplay of CorsixTH?
      description: This will help developers decide if it is a worthwhile endeavour
    validations:
      required: true
# Original feature?
  - type: dropdown
    id: original-presence
    attributes:
      label: Was the feature in the original game?
      options:
        - "Yes"
        - "No"
        - Unsure
    validations:
      required: true
# CorsixTH version
  - type: input
    id: corsix-version
    attributes:
      label: What version of CorsixTH are you using?
      description: "You can check and download the latest stable release at https://github.com/CorsixTH/CorsixTH/releases"
      placeholder: e.g. 0.65 (release version) or 7d886f35ca (if built from master)
    validations:
      required: true
# Related issues
  - type: input
    id: existing-issue
    attributes:
      label: Does this feature/enhancement relate to a current problem?
      description: Give a summary of the problem -- referencing an issue number if one exists
      value: "No"
# Extra Info
  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Add any other information or screenshots about the feature request here
  ### EOF
