var annotated_dup =
[
    [ "th", "namespaceth.html", [
      [ "sound", "namespaceth_1_1sound.html", [
        [ "sdl_mixer", "classth_1_1sound_1_1sdl__mixer.html", "classth_1_1sound_1_1sdl__mixer" ]
      ] ]
    ] ],
    [ "abstract_pathfinder", "classabstract__pathfinder.html", "classabstract__pathfinder" ],
    [ "abstract_window", "classabstract__window.html", null ],
    [ "animation", "classanimation.html", "classanimation" ],
    [ "animation_base", "classanimation__base.html", "classanimation__base" ],
    [ "animation_key", "structanimation__key.html", "structanimation__key" ],
    [ "animation_manager", "classanimation__manager.html", "classanimation__manager" ],
    [ "animation_start_frames", "structanimation__start__frames.html", "structanimation__start__frames" ],
    [ "basic_pathfinder", "classbasic__pathfinder.html", "classbasic__pathfinder" ],
    [ "bitmap_font", "classbitmap__font.html", "classbitmap__font" ],
    [ "chunk_renderer", "classchunk__renderer.html", "classchunk__renderer" ],
    [ "clip_rect", "structclip__rect.html", "structclip__rect" ],
    [ "cursor", "classcursor.html", "classcursor" ],
    [ "drawable", "structdrawable.html", "structdrawable" ],
    [ "font", "classfont.html", "classfont" ],
    [ "font_shadow_options", "structfont__shadow__options.html", "structfont__shadow__options" ],
    [ "freetype_font", "classfreetype__font.html", "classfreetype__font" ],
    [ "full_colour_renderer", "classfull__colour__renderer.html", "classfull__colour__renderer" ],
    [ "full_colour_storing", "classfull__colour__storing.html", "classfull__colour__storing" ],
    [ "hospital_finder", "classhospital__finder.html", "classhospital__finder" ],
    [ "idle_tile_finder", "classidle__tile__finder.html", "classidle__tile__finder" ],
    [ "integer_run_length_decoder", "classinteger__run__length__decoder.html", "classinteger__run__length__decoder" ],
    [ "integer_run_length_encoder", "classinteger__run__length__encoder.html", "classinteger__run__length__encoder" ],
    [ "iso_filesystem", "classiso__filesystem.html", "classiso__filesystem" ],
    [ "layers", "structlayers.html", "structlayers" ],
    [ "level_map", "classlevel__map.html", "classlevel__map" ],
    [ "lfs_ext", "classlfs__ext.html", null ],
    [ "line_sequence", "classline__sequence.html", "classline__sequence" ],
    [ "link_list", "classlink__list.html", "classlink__list" ],
    [ "load_multi_buffer", "classload__multi__buffer.html", "classload__multi__buffer" ],
    [ "lua_class_binding", "classlua__class__binding.html", "classlua__class__binding" ],
    [ "lua_persist_basic_reader", "classlua__persist__basic__reader.html", "classlua__persist__basic__reader" ],
    [ "lua_persist_basic_writer", "classlua__persist__basic__writer.html", "classlua__persist__basic__writer" ],
    [ "lua_persist_int", "structlua__persist__int.html", null ],
    [ "lua_persist_int&lt; int &gt;", "structlua__persist__int_3_01int_01_4.html", "structlua__persist__int_3_01int_01_4" ],
    [ "lua_persist_reader", "classlua__persist__reader.html", "classlua__persist__reader" ],
    [ "lua_persist_writer", "classlua__persist__writer.html", "classlua__persist__writer" ],
    [ "lua_register_state", "structlua__register__state.html", "structlua__register__state" ],
    [ "lua_state_deleter", "classlua__state__deleter.html", "classlua__state__deleter" ],
    [ "luaT_classinfo", "structluaT__classinfo.html", null ],
    [ "luaT_classinfo&lt; abstract_window &gt;", "structluaT__classinfo_3_01abstract__window_01_4.html", null ],
    [ "luaT_classinfo&lt; animation &gt;", "structluaT__classinfo_3_01animation_01_4.html", null ],
    [ "luaT_classinfo&lt; animation_manager &gt;", "structluaT__classinfo_3_01animation__manager_01_4.html", null ],
    [ "luaT_classinfo&lt; bitmap_font &gt;", "structluaT__classinfo_3_01bitmap__font_01_4.html", null ],
    [ "luaT_classinfo&lt; cursor &gt;", "structluaT__classinfo_3_01cursor_01_4.html", null ],
    [ "luaT_classinfo&lt; font &gt;", "structluaT__classinfo_3_01font_01_4.html", null ],
    [ "luaT_classinfo&lt; freetype_font &gt;", "structluaT__classinfo_3_01freetype__font_01_4.html", null ],
    [ "luaT_classinfo&lt; iso_filesystem &gt;", "structluaT__classinfo_3_01iso__filesystem_01_4.html", null ],
    [ "luaT_classinfo&lt; layers &gt;", "structluaT__classinfo_3_01layers_01_4.html", null ],
    [ "luaT_classinfo&lt; level_map &gt;", "structluaT__classinfo_3_01level__map_01_4.html", null ],
    [ "luaT_classinfo&lt; lfs_ext &gt;", "structluaT__classinfo_3_01lfs__ext_01_4.html", null ],
    [ "luaT_classinfo&lt; line_sequence &gt;", "structluaT__classinfo_3_01line__sequence_01_4.html", null ],
    [ "luaT_classinfo&lt; movie_player &gt;", "structluaT__classinfo_3_01movie__player_01_4.html", null ],
    [ "luaT_classinfo&lt; music &gt;", "structluaT__classinfo_3_01music_01_4.html", null ],
    [ "luaT_classinfo&lt; palette &gt;", "structluaT__classinfo_3_01palette_01_4.html", null ],
    [ "luaT_classinfo&lt; pathfinder &gt;", "structluaT__classinfo_3_01pathfinder_01_4.html", null ],
    [ "luaT_classinfo&lt; raw_bitmap &gt;", "structluaT__classinfo_3_01raw__bitmap_01_4.html", null ],
    [ "luaT_classinfo&lt; render_target &gt;", "structluaT__classinfo_3_01render__target_01_4.html", null ],
    [ "luaT_classinfo&lt; sound_archive &gt;", "structluaT__classinfo_3_01sound__archive_01_4.html", null ],
    [ "luaT_classinfo&lt; sound_player &gt;", "structluaT__classinfo_3_01sound__player_01_4.html", null ],
    [ "luaT_classinfo&lt; sprite_render_list &gt;", "structluaT__classinfo_3_01sprite__render__list_01_4.html", null ],
    [ "luaT_classinfo&lt; sprite_sheet &gt;", "structluaT__classinfo_3_01sprite__sheet_01_4.html", null ],
    [ "luaT_classinfo&lt; string_proxy &gt;", "structluaT__classinfo_3_01string__proxy_01_4.html", null ],
    [ "luaT_classinfo&lt; th_lua_midi_player &gt;", "structluaT__classinfo_3_01th__lua__midi__player_01_4.html", null ],
    [ "map_flags_overlay", "classmap__flags__overlay.html", "classmap__flags__overlay" ],
    [ "map_overlay", "classmap__overlay.html", "classmap__overlay" ],
    [ "map_overlay_pair", "classmap__overlay__pair.html", "classmap__overlay__pair" ],
    [ "map_parcels_overlay", "classmap__parcels__overlay.html", "classmap__parcels__overlay" ],
    [ "map_positions_overlay", "classmap__positions__overlay.html", "classmap__positions__overlay" ],
    [ "map_scanline_iterator", "classmap__scanline__iterator.html", "classmap__scanline__iterator" ],
    [ "map_text_overlay", "classmap__text__overlay.html", "classmap__text__overlay" ],
    [ "map_tile", "structmap__tile.html", "structmap__tile" ],
    [ "map_tile_flags", "structmap__tile__flags.html", "structmap__tile__flags" ],
    [ "map_tile_iterator", "classmap__tile__iterator.html", "classmap__tile__iterator" ],
    [ "map_typical_overlay", "classmap__typical__overlay.html", "classmap__typical__overlay" ],
    [ "memory_buffer", "classmemory__buffer.html", "classmemory__buffer" ],
    [ "memory_reader", "classmemory__reader.html", "classmemory__reader" ],
    [ "midi_player", "classmidi__player.html", null ],
    [ "midi_token", "structmidi__token.html", "structmidi__token" ],
    [ "movie_player", "classmovie__player.html", "classmovie__player" ],
    [ "music", "classmusic.html", "classmusic" ],
    [ "object_visitor", "classobject__visitor.html", "classobject__visitor" ],
    [ "palette", "classpalette.html", "classpalette" ],
    [ "path_node", "structpath__node.html", "structpath__node" ],
    [ "pathfinder", "classpathfinder.html", "classpathfinder" ],
    [ "raw_bitmap", "classraw__bitmap.html", "classraw__bitmap" ],
    [ "render_size", "structrender__size.html", "structrender__size" ],
    [ "render_target", "classrender__target.html", "classrender__target" ],
    [ "render_target_creation_params", "structrender__target__creation__params.html", "structrender__target__creation__params" ],
    [ "sound_archive", "classsound__archive.html", "classsound__archive" ],
    [ "sound_player", "classsound__player.html", "classsound__player" ],
    [ "sprite_render_list", "classsprite__render__list.html", "classsprite__render__list" ],
    [ "sprite_sheet", "classsprite__sheet.html", "classsprite__sheet" ],
    [ "string_proxy", "classstring__proxy.html", null ],
    [ "text_layout", "structtext__layout.html", "structtext__layout" ],
    [ "th_element_properties", "structth__element__properties.html", "structth__element__properties" ],
    [ "th_frame_properties", "structth__frame__properties.html", "structth__frame__properties" ],
    [ "th_lua_midi_player", "classth__lua__midi__player.html", null ],
    [ "th_sprite_properties", "structth__sprite__properties.html", "structth__sprite__properties" ],
    [ "th_string_list", "classth__string__list.html", "classth__string__list" ],
    [ "window_size", "structwindow__size.html", "structwindow__size" ],
    [ "wx_storing", "classwx__storing.html", "classwx__storing" ],
    [ "xy_pair", "structxy__pair.html", "structxy__pair" ]
];