--- 
-- Calling "execute script" while CorsixTH is running will execute the latest code in this script
-- so you don't need to restart CorsixTH.
-- 
-- Like with the console you can reference clicked humanoids with the underscore global variable so
-- for example: _:die() will make a clicked patient die.
-- 
-- The run time App class instance can be referenced with its global variable "TheApp", with it you
-- can reference other run time class instances like: TheApp.world
---
