var dir_1646eab6995556d59b95ff4b2090d7c0 =
[
    [ "Disease.java", "Disease_8java.html", "Disease_8java" ],
    [ "Emergency.java", "Emergency_8java.html", "Emergency_8java" ],
    [ "FileChooser.java", "FileChooser_8java.html", "FileChooser_8java" ],
    [ "GridPanel.java", "GridPanel_8java.html", "GridPanel_8java" ],
    [ "Gui.java", "Gui_8java.html", "Gui_8java" ],
    [ "Main.java", "Main_8java.html", "Main_8java" ],
    [ "Menu.java", "Menu_8java.html", "Menu_8java" ],
    [ "Population.java", "Population_8java.html", "Population_8java" ],
    [ "Quake.java", "Quake_8java.html", "Quake_8java" ],
    [ "ReaderWriter.java", "ReaderWriter_8java.html", "ReaderWriter_8java" ],
    [ "StaffLevels.java", "StaffLevels_8java.html", "StaffLevels_8java" ],
    [ "StartStaff.java", "StartStaff_8java.html", "StartStaff_8java" ],
    [ "TabAwards.java", "TabAwards_8java.html", "TabAwards_8java" ],
    [ "TabBar.java", "TabBar_8java.html", "TabBar_8java" ],
    [ "TabDiseases.java", "TabDiseases_8java.html", "TabDiseases_8java" ],
    [ "TabEarthquakes.java", "TabEarthquakes_8java.html", "TabEarthquakes_8java" ],
    [ "TabEmergencies.java", "TabEmergencies_8java.html", "TabEmergencies_8java" ],
    [ "TabGeneral.java", "TabGeneral_8java.html", "TabGeneral_8java" ],
    [ "TabGoals.java", "TabGoals_8java.html", "TabGoals_8java" ],
    [ "TabObjects.java", "TabObjects_8java.html", "TabObjects_8java" ],
    [ "TabPopulation.java", "TabPopulation_8java.html", "TabPopulation_8java" ],
    [ "TabStaff.java", "TabStaff_8java.html", "TabStaff_8java" ],
    [ "VarManipulator.java", "VarManipulator_8java.html", "VarManipulator_8java" ]
];