#!/bin/bash
set -ev
# Build LevelEdit
cd $TRAVIS_BUILD_DIR/LevelEdit && ant dist
# Build documentation
cd ${TRAVIS_BUILD_DIR}/fresh && make doc
# Upload new docs
if [ $TRAVIS_REPO_SLUG == "CorsixTH/CorsixTH" -a $TRAVIS_BRANCH == "master" ]; then sshpass -p "$SCP_PASS" scp -r -v -P12349 $TRAVIS_BUILD_DIR/fresh/doc/* cthbuilder@server2.armedpineapple.co.uk:/home/cthbuilder/docs/; fi;
