#!/bin/bash
set -ev
  # Get build dependencies
sudo apt-get -qq update
sudo apt-get -q install p7zip-full build-essential sshpass lua5.1 luarocks doxygen
  # Required for LDocGen
sudo luarocks install lpeg
sudo luarocks install luafilesystem
  # Required for lua unit tests
sudo luarocks install busted
  # Install the mingw-w64 packages.
sudo apt-get -q install g++-mingw-w64 gcc-mingw-w64 g++-mingw-w64-i686 gcc-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
  # The packages in ubuntu's repositories seem a little broken
  # so use a bleeding edge version
wget http://ftp.jp.debian.org/debian/pool/main/m/mingw-w64/mingw-w64_3.2.0-2_all.deb
sudo dpkg -i mingw-w64_3.2.0-2_all.deb
mkdir libs
cd libs
  # Get FFmpeg
wget http://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-2.5.2-win32-dev.7z
wget http://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-2.5.2-win32-shared.7z
/usr/bin/7za x ffmpeg-2.5.2-win32-dev.7z
/usr/bin/7za x ffmpeg-2.5.2-win32-shared.7z
mv ffmpeg-2.5.2-win32-dev ffmpeg-dev
mv ffmpeg-2.5.2-win32-shared ffmpeg-bin
  # Get freetype
wget https://github.com/CorsixTH/deps/raw/master/travisci-mingw/freetype-2.3.5-1-lib.zip
wget https://github.com/CorsixTH/deps/raw/master/travisci-mingw/freetype-2.3.5-1-bin.zip
wget https://github.com/CorsixTH/deps/raw/master/travisci-mingw/freetype-2.3.5-1-dep.zip
unzip -n freetype-2.3.5-1-lib.zip -d freetype
unzip -n freetype-2.3.5-1-bin.zip -d freetype
unzip -n freetype-2.3.5-1-dep.zip -d freetype
  # Get SDL
wget http://libsdl.org/release/SDL2-devel-2.0.3-mingw.tar.gz
wget https://raw.githubusercontent.com/CorsixTH/deps/master/travisci-mingw/patches/SDL_mingw_build_fix.patch
tar xfz SDL2-devel-2.0.3-mingw.tar.gz
patch -p2 -d SDL2-2.0.3/i686-w64-mingw32/include/SDL2 < SDL_mingw_build_fix.patch
sudo mkdir /usr/i686-w64-mingw32/bin/
sudo cp SDL2-2.0.3/i686-w64-mingw32/bin/* /usr/i686-w64-mingw32/bin/
sudo cp -r SDL2-2.0.3/i686-w64-mingw32/include/SDL2/* /usr/i686-w64-mingw32/include/
sudo cp -r SDL2-2.0.3/i686-w64-mingw32/lib/* /usr/i686-w64-mingw32/lib/
sudo chmod +x /usr/i686-w64-mingw32/bin/sdl2-config
  # Get SDL Mixer
wget http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.0-mingw.tar.gz
tar xfz SDL2_mixer-devel-2.0.0-mingw.tar.gz
sudo cp -r SDL2_mixer-2.0.0/i686-w64-mingw32/include/SDL2/* /usr/i686-w64-mingw32/include/
sudo cp -r SDL2_mixer-2.0.0/i686-w64-mingw32/lib/* /usr/i686-w64-mingw32/lib/
mkdir lua
  # Get LUA
wget http://sourceforge.net/projects/mingw/files/MinGW/Extension/lua/lua-5.1.4-4/lua-5.1.4-4-mingw32-dll-51.tar.xz
tar xJf lua-5.1.4-4-mingw32-dll-51.tar.xz -C lua
wget http://sourceforge.net/projects/mingw/files/MinGW/Extension/lua/lua-5.1.4-4/lua-5.1.4-4-mingw32-dev.tar.xz
tar xJf lua-5.1.4-4-mingw32-dev.tar.xz -C lua
  # Get LuaFileSystem
wget http://github.com/keplerproject/luafilesystem/archive/v_1_6_3.tar.gz
tar xzf v_1_6_3.tar.gz
pushd luafilesystem-v_1_6_3
i686-w64-mingw32-gcc -O2 -c -o src/lfs.o src/lfs.c -I../lua/include
i686-w64-mingw32-gcc -shared -o lfs.dll src/lfs.o ../lua/bin/lua51.dll
popd
  # Get LPeg
wget http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-0.12.1.tar.gz
tar xzf lpeg-0.12.1.tar.gz
pushd lpeg-0.12.1
i686-w64-mingw32-gcc -std=c99 -O2 -I../lua/include -c -o lpcap.o lpcap.c
i686-w64-mingw32-gcc -std=c99 -O2 -I../lua/include -c -o lpcode.o lpcode.c
i686-w64-mingw32-gcc -std=c99 -O2 -I../lua/include -c -o lpprint.o lpprint.c
i686-w64-mingw32-gcc -std=c99 -O2 -I../lua/include -c -o lptree.o lptree.c
i686-w64-mingw32-gcc -std=c99 -O2 -I../lua/include -c -o lpvm.o lpvm.c
i686-w64-mingw32-gcc -shared -o lpeg.dll lpcap.o lpcode.o lpprint.o lptree.o lpvm.o ../lua/bin/lua51.dll
popd
git clone https://github.com/diegonehab/luasocket.git luasocket
pushd luasocket
git checkout 5edf093
make PLAT=mingw LUAINC_mingw=$TRAVIS_BUILD_DIR/libs/lua/include LUALIB_mingw=$TRAVIS_BUILD_DIR/libs/lua/bin/lua51.dll CC_mingw=i686-w64-mingw32-gcc LD_mingw=i686-w64-mingw32-gcc prefix=$TRAVIS_BUILD_DIR/libs/luasocket LUAV=5.1
make PLAT=mingw LUAINC_mingw=$TRAVIS_BUILD_DIR/libs/lua/include LUALIB_mingw=$TRAVIS_BUILD_DIR/libs/lua/bin/lua51.dll CC_mingw=i686-w64-mingw32-gcc LD_mingw=i686-w64-mingw32-gcc prefix=$TRAVIS_BUILD_DIR/libs/luasocket LUAV=5.1 install
mkdir $TRAVIS_BUILD_DIR/LevelEdit/bin
