/* XPM */
static const char *const backdrop_xpm[] = {
"126 64 12 1",
"f c #695D7D",
"c c #6D6D6D",
". c #797979",
"j c #3561CA",
"i c #797196",
"d c #8275A2",
"b c #867DAA",
"e c Gray51",
"a c #8E8E8E",
"g c #A29A9E",
"h c #AAAAAA",
"  c None",
"                              ..                                                              ..                              ",
"                            abcccd                                                          abcccd                            ",
"                          abccccccce                                                      abccccccce                          ",
"                        abcfcfcfcfcfcb                                                  abcfcfcfcfcfcb                        ",
"                      agacccccfcfcfcccag                                              agacccccfcfcfcccag                      ",
"                    eahhhabfcfcfcfcfbahhha                                          eahhhabfcfcfcfcfbahhha                    ",
"                  eahhhhhhhabfffffbahhhhhhha                                      eahhhhhhhabfffffbahhhhhhha                  ",
"                iahhhhhhhhhhha.f.ahhhhhhhhhhha                                  iahhhhhhhhhhha.f.ahhhhhhhhhhha                ",
"              ...hhhhhhhhhhhhh...hhhhhhhhhhhhh..                              ...hhhhhhhhhhhhh...hhhhhhhhhhhhh..              ",
"            abcccdahhhhhhhhhadcccdahhhhhhhhhabcccd                          abcccdahhhhhhhhhadcccdahhhhhhhhhabcccd            ",
"          abccccccceahhhhhaeccccccceahhhhhabccccccce                      abccccccceahhhhhaeccccccceahhhhhabccccccce          ",
"        abcfcfcfcfcfcbahgbcfcfcfcfcfcbahabcfcfcfcfcfcb                  abcfcfcfcfcfcbahgbcfcfcfcfcfcbahabcfcfcfcfcfcb        ",
"      agacccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcccag              agacccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcccag      ",
"    eahhhabfcfcfcfcfbahhhabfcfcfcfcfeahhhabfcfcfcfcfbahhha          eahhhabfcfcfcfcfbahhhabfcfcfcfcfeahhhabfcfcfcfcfbahhha    ",
"  eahhhhhhhabfffffbahhhhhhhabfffffeahhhhhhhabfffffbahhhhhhha      eahhhhhhhabfffffbahhhhhhhabfffffeahhhhhhhabfffffbahhhhhhha  ",
"iahhhhhhhhhhha.f.ahhhhhhhhhhha.fiahhhhhhhhhhha.f.ahhhhhhhhhhha  iahhhhhhhhhhha.f.ahhhhhhhhhhha.fiahhhhhhhhhhha.f.ahhhhhhhhhhha",
".hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhhjj.hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh",
"  ahhhhhhhhhadcccdahhhhhhhhhabcccdahhhhhhhhhadcccdahhhhhhhhhjjccjjahhhhhhhhhadcccdahhhhhhhhhabcccdahhhhhhhhhadcccdahhhhhhhhh  ",
"    ahhhhhaeccccccceahhhhhabccccccceahhhhhaeccccccceahhhhhjjccccccjjahhhhhaeccccccceahhhhhabccccccceahhhhhaeccccccceahhhhh    ",
"      ahgbcfcfcfcfcfcbahabcfcfcfcfcfcbahgbcfcfcfcfcfcbahjjcfcfcfcfcfjjahgbcfcfcfcfcfcbahabcfcfcfcfcfcbahgbcfcfcfcfcfcbah      ",
"        acccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcccjjacccccfcfcfcccjjacccccfcfcfcccagacccccfcfcfcccagacccccfcfcfccc        ",
"          bfcfcfcfcfeahhhabfcfcfcfcfbahhhabfcfcfcfcfjjhhhabfcfcfcfcfbahhjjbfcfcfcfcfeahhhabfcfcfcfcfbahhhabfcfcfcfcf          ",
"            bfffffeahhhhhhhabfffffbahhhhhhhabfffffjjhhhhhhhabfffffbahhhhhhjjbfffffeahhhhhhhabfffffbahhhhhhhabfffff            ",
"              .fiahhhhhhhhhhha.f.ahhhhhhhhhhha.fjjhhhhhhhhhhha.f.ahhhhhhhhhhjj.fiahhhhhhhhhhha.f.ahhhhhhhhhhha.f              ",
"                .hhhhhhhhhhhhh...hhhhhhhhhhhhhjj.hhhhhhhhhhhhh...hhhhhhhhhhhhhjj.hhhhhhhhhhhhh...hhhhhhhhhhhhh                ",
"                  ahhhhhhhhhadcccdahhhhhhhhhjjcccdahhhhhhhhhadcccdahhhhhhhhhabccjjahhhhhhhhhadcccdahhhhhhhhh                  ",
"                    ahhhhhaeccccccceahhhhhjjccccccceahhhhhaeccccccceahhhhhabccccccjjahhhhhaeccccccceahhhhh                    ",
"                      ahgbcfcfcfcfcfcbahjjcfcfcfcfcfcbahgbcfcfcfcfcfcbahabcfcfcfcfcfjjahgbcfcfcfcfcfcbah                      ",
"                        acccccfcfcfcccjjacccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcccjjacccccfcfcfccc                        ",
"                          bfcfcfcfcfjjhhhabfcfcfcfcfbahhhabfcfcfcfcfeahhhabfcfcfcfcfbahhjjbfcfcfcfcf                          ",
"                            bfffffjjhhhhhhhabfffffbahhhhhhhabfffffeahhhhhhhabfffffbahhhhhhjjbfffff                            ",
"                              .fjjhhhhhhhhhhha.f.ahhhhhhhhhhha.fiahhhhhhhhhhha.f.ahhhhhhhhhhjj.f                              ",
"                              ..jjhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhjj..                              ",
"                            abcccdjjhhhhhhhhadcccdahhhhhhhhhabcccdahhhhhhhhhadcccdahhhhhhhjjabcccd                            ",
"                          abcccccccejjhhhhaeccccccceahhhhhabccccccceahhhhhaeccccccceahhhjjabccccccce                          ",
"                        abcfcfcfcfcfcbjjgbcfcfcfcfcfcbahabcfcfcfcfcfcbahgbcfcfcfcfcfcbjjabcfcfcfcfcfcb                        ",
"                      agacccccfcfcfcccagjjccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcjjagacccccfcfcfcccag                      ",
"                    eahhhabfcfcfcfcfbahhhajjcfcfcfcfeahhhabfcfcfcfcfbahhhabfcfcfcfjjeahhhabfcfcfcfcfbahhha                    ",
"                  eahhhhhhhabfffffbahhhhhhhajjffffeahhhhhhhabfffffbahhhhhhhabfffjjeahhhhhhhabfffffbahhhhhhha                  ",
"                iahhhhhhhhhhha.f.ahhhhhhhhhhhajjiahhhhhhhhhhha.f.ahhhhhhhhhhhajjiahhhhhhhhhhha.f.ahhhhhhhhhhha                ",
"              ...hhhhhhhhhhhhh...hhhhhhhhhhhhh..jjhhhhhhhhhhhh...hhhhhhhhhhhjj...hhhhhhhhhhhhh...hhhhhhhhhhhhh..              ",
"            abcccdahhhhhhhhhadcccdahhhhhhhhhabcccdjjhhhhhhhhadcccdahhhhhhhjjabcccdahhhhhhhhhadcccdahhhhhhhhhabcccd            ",
"          abccccccceahhhhhaeccccccceahhhhhabcccccccejjhhhhaeccccccceahhhjjabccccccceahhhhhaeccccccceahhhhhabccccccce          ",
"        abcfcfcfcfcfcbahgbcfcfcfcfcfcbahabcfcfcfcfcfcbjjgbcfcfcfcfcfcbjjabcfcfcfcfcfcbahgbcfcfcfcfcfcbahabcfcfcfcfcfcb        ",
"      agacccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcccagjjccccfcfcfcjjagacccccfcfcfcccagacccccfcfcfcccagacccccfcfcfcccag      ",
"    eahhhabfcfcfcfcfbahhhabfcfcfcfcfeahhhabfcfcfcfcfbahhhajjcfcfcfjjeahhhabfcfcfcfcfbahhhabfcfcfcfcfeahhhabfcfcfcfcfbahhha    ",
"  eahhhhhhhabfffffbahhhhhhhabfffffeahhhhhhhabfffffbahhhhhhhajjffjjeahhhhhhhabfffffbahhhhhhhabfffffeahhhhhhhabfffffbahhhhhhha  ",
"iahhhhhhhhhhha.f.ahhhhhhhhhhha.fiahhhhhhhhhhha.f.ahhhhhhhhhhhajjiahhhhhhhhhhha.f.ahhhhhhhhhhha.fiahhhhhhhhhhha.f.ahhhhhhhhhhha",
".hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh  .hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh...hhhhhhhhhhhhh",
"  ahhhhhhhhhadcccdahhhhhhhhhabcccdahhhhhhhhhadcccdahhhhhhhhh      ahhhhhhhhhadcccdahhhhhhhhhabcccdahhhhhhhhhadcccdahhhhhhhhh  ",
"    ahhhhhaeccccccceahhhhhabccccccceahhhhhaeccccccceahhhhh          ahhhhhaeccccccceahhhhhabccccccceahhhhhaeccccccceahhhhh    ",
"      ahgbcfcfcfcfcfcbahabcfcfcfcfcfcbahgbcfcfcfcfcfcbah              ahgbcfcfcfcfcfcbahabcfcfcfcfcfcbahgbcfcfcfcfcfcbah      ",
"        acccccfcfcfcccagacccccfcfcfcccagacccccfcfcfccc                  acccccfcfcfcccagacccccfcfcfcccagacccccfcfcfccc        ",
"          bfcfcfcfcfeahhhabfcfcfcfcfbahhhabfcfcfcfcf                      bfcfcfcfcfeahhhabfcfcfcfcfbahhhabfcfcfcfcf          ",
"            bfffffeahhhhhhhabfffffbahhhhhhhabfffff                          bfffffeahhhhhhhabfffffbahhhhhhhabfffff            ",
"              .fiahhhhhhhhhhha.f.ahhhhhhhhhhha.f                              .fiahhhhhhhhhhha.f.ahhhhhhhhhhha.f              ",
"                .hhhhhhhhhhhhh...hhhhhhhhhhhhh                                  .hhhhhhhhhhhhh...hhhhhhhhhhhhh                ",
"                  ahhhhhhhhhadcccdahhhhhhhhh                                      ahhhhhhhhhadcccdahhhhhhhhh                  ",
"                    ahhhhhaeccccccceahhhhh                                          ahhhhhaeccccccceahhhhh                    ",
"                      ahgbcfcfcfcfcfcbah                                              ahgbcfcfcfcfcfcbah                      ",
"                        acccccfcfcfccc                                                  acccccfcfcfccc                        ",
"                          bfcfcfcfcf                                                      bfcfcfcfcf                          ",
"                            bfffff                                                          bfffff                            ",
"                              .f                                                              .f                              "
};
